trying to run ============================= test session starts ============================== platform linux -- Python 3.12.3, pytest-8.3.4, pluggy-1.5.0 -- /home/courcol/DEV/test-db/.venv/bin/python3 cachedir: .pytest_cache rootdir: /home/courcol/DEV/test-db configfile: pyproject.toml testpaths: test plugins: anyio-4.6.2.post1, cov-6.0.0 collecting ... collected 14 items
test/test_contribution.py::test_create_contribution PASSED               [  7%]
test/test_experimental_bouton_density.py::test_experimental_bouton_density PASSED [ 14%]
test/test_experimental_neuron_density.py::test_experimental_neuron_density PASSED [ 21%]
test/test_license.py::test_create_license PASSED                         [ 28%]
test/test_morphology.py::test_create_species PASSED                      [ 35%]
test/test_morphology.py::test_create_strain PASSED                       [ 42%]
test/test_morphology.py::test_create_reconstruction_morphology PASSED    [ 50%]
test/test_morphology.py::test_create_annotation PASSED                   [ 57%]
test/test_organization.py::test_create_organization PASSED               [ 64%]
test/test_person.py::test_create_person PASSED                           [ 71%]
test/test_role.py::test_create_person PASSED                             [ 78%]
test/test_species.py::test_create_species PASSED                         [ 85%]
test/test_strain.py::test_create_strain PASSED                           [ 92%]
test/test_synapses_per_connection.py::test_experimental_synapses_per_connection PASSED [100%]
ERROR: Coverage failure: total of 55 is less than fail-under=80

=============================== warnings summary ===============================
.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:295: 17 warnings
  /home/courcol/DEV/test-db/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:295: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)

.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:345
  /home/courcol/DEV/test-db/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:345: UserWarning: Valid config keys have changed in V2:
  * 'orm_mode' has been renamed to 'from_attributes'
    warnings.warn(message, UserWarning)

app/models/base.py:20
  /home/courcol/DEV/test-db/app/models/base.py:20: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    Base = declarative_base()

.venv/lib/python3.12/site-packages/_pytest/config/__init__.py:1441
  /home/courcol/DEV/test-db/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py:1441: PytestConfigWarning: Unknown config option: asyncio_mode

    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

test/test_contribution.py::test_create_contribution
test/test_morphology.py::test_create_reconstruction_morphology
test/test_morphology.py::test_create_annotation
  /home/courcol/DEV/test-db/app/routers/morphology.py:65: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
    brain_location = BrainLocation(**recontruction.brain_location.dict())

test/test_experimental_bouton_density.py::test_experimental_bouton_density
  /home/courcol/DEV/test-db/app/routers/experimental_bouton_density.py:48: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
    dump["brain_location"] = BrainLocation(**density.brain_location.dict())

test/test_experimental_neuron_density.py::test_experimental_neuron_density
  /home/courcol/DEV/test-db/app/routers/experimental_neuron_density.py:48: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
    dump["brain_location"] = BrainLocation(**density.brain_location.dict())

test/test_morphology.py::test_create_annotation
test/test_morphology.py::test_create_annotation
test/test_morphology.py::test_create_annotation
test/test_morphology.py::test_create_annotation
test/test_morphology.py::test_create_annotation
test/test_morphology.py::test_create_annotation
test/test_morphology.py::test_create_annotation
test/test_morphology.py::test_create_annotation
  /home/courcol/DEV/test-db/app/__init__.py:84: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
    MorphologyMeasurementSerieElement(**serie.dict())

test/test_morphology.py::test_create_annotation
  /home/courcol/DEV/test-db/app/routers/morphology.py:52: PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
    ret = ReconstructionMorphologyExpand.from_orm(rm).dict()

test/test_morphology.py::test_create_annotation
  /home/courcol/DEV/test-db/app/schemas/base.py:12: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
    result = super().dict(**kwargs)

test/test_synapses_per_connection.py::test_experimental_synapses_per_connection
  /home/courcol/DEV/test-db/app/routers/experimental_synapses_per_connection.py:48: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
    dump["brain_location"] = BrainLocation(**density.brain_location.dict())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.12.3-final-0 -----------
Name                                                  Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------------------
app/__init__.py                                          73      3      6      1    95%   100-101, 125
app/cli/__init__.py                                       0      0      0      0   100%
app/cli/curate.py                                        35     35     20      0     0%   1-64
app/cli/import-data.py                                  320    320    100      0     0%   1-562
app/config.py                                             2      0      0      0   100%
app/dependencies/__init__.py                              0      0      0      0   100%
app/dependencies/db.py                                    6      4      0      0    33%   4-8
app/models/__init__.py                                    0      0      0      0   100%
app/models/agent.py                                      31      0      0      0   100%
app/models/annotation.py                                 33     33      0      0     0%   1-47
app/models/base.py                                       81      2      0      0    98%   34, 36
app/models/contribution.py                               15      0      0      0   100%
app/models/density.py                                    22      0      0      0   100%
app/models/morphology.py                                 29      0      0      0   100%
app/models/role.py                                        8      0      0      0   100%
app/models/single_cell_experimental_trace.py             10     10      0      0     0%   1-22
app/routers/__init__.py                                   0      0      0      0   100%
app/routers/contribution.py                              27      3      2      1    86%   28, 56-57
app/routers/experimental_bouton_density.py               30      3      4      2    85%   35, 47->50, 61-62
app/routers/experimental_neuron_density.py               30      3      4      2    85%   35, 47->50, 61-62
app/routers/experimental_synapses_per_connection.py      30      3      4      2    85%   35, 47->50, 61-62
app/routers/morphology.py                                34      3      6      2    88%   39, 64->66, 87-88
app/routers/organization.py                              26      1      2      1    93%   25
app/routers/person.py                                    26      1      2      1    93%   25
app/routers/role.py                                      25      1      2      1    93%   22
app/schemas/__init__.py                                   0      0      0      0   100%
app/schemas/agent.py                                     26      0      0      0   100%
app/schemas/base.py                                      78      0      0      0   100%
app/schemas/contribution.py                              18      0      0      0   100%
app/schemas/density.py                                   31      0      0      0   100%
app/schemas/morphology.py                                29      0      0      0   100%
app/schemas/role.py                                      12      0      0      0   100%
-------------------------------------------------------------------------------------------------
TOTAL                                                  1087    425    152     13    55%

FAIL Required test coverage of 80.0% not reached. Total coverage: 54.96%
============================= slowest 10 durations =============================
0.13s call     test/test_contribution.py::test_create_contribution
0.06s call     test/test_morphology.py::test_create_annotation
0.04s call     test/test_synapses_per_connection.py::test_experimental_synapses_per_connection
0.04s call     test/test_experimental_neuron_density.py::test_experimental_neuron_density
0.04s call     test/test_experimental_bouton_density.py::test_experimental_bouton_density
0.03s call     test/test_morphology.py::test_create_reconstruction_morphology
0.02s setup    test/test_contribution.py::test_create_contribution
0.02s call     test/test_organization.py::test_create_organization
0.01s call     test/test_person.py::test_create_person
0.01s setup    test/test_role.py::test_create_person
======================= 14 passed, 36 warnings in 0.75s ========================